name: Windows Event Log Security
id: e3e44de1-57b1-462d-b57c-c7657af7ae6e
version: 1
date: '2024-07-18'
author: Patrick Bareiss, Splunk
source: XmlWinEventLog:Security
sourcetype: xmlwineventlog
separator: EventCode
supported_TA:
- name: Splunk Add-on for Microsoft Windows
  url: https://splunkbase.splunk.com/app/742
  version: 8.8.0
description: Data source object for Windows Event Log Security
event_sources:
- Windows Event Log Security 1100
- Windows Event Log Security 1102
- Windows Event Log Security 4624
- Windows Event Log Security 4625
- Windows Event Log Security 4627
- Windows Event Log Security 4648
- Windows Event Log Security 4662
- Windows Event Log Security 4663
- Windows Event Log Security 4672
- Windows Event Log Security 4688
- Windows Event Log Security 4698
- Windows Event Log Security 4699
- Windows Event Log Security 4703
- Windows Event Log Security 4719
- Windows Event Log Security 4720
- Windows Event Log Security 4724
- Windows Event Log Security 4725
- Windows Event Log Security 4726
- Windows Event Log Security 4732
- Windows Event Log Security 4738
- Windows Event Log Security 4739
- Windows Event Log Security 4741
- Windows Event Log Security 4742
- Windows Event Log Security 4768
- Windows Event Log Security 4769
- Windows Event Log Security 4771
- Windows Event Log Security 4776
- Windows Event Log Security 4781
- Windows Event Log Security 4794
- Windows Event Log Security 4798
- Windows Event Log Security 4876
- Windows Event Log Security 4886
- Windows Event Log Security 4887
- Windows Event Log Security 5136
- Windows Event Log Security 5137
- Windows Event Log Security 5140
- Windows Event Log Security 5141
- Windows Event Log Security 5145
