name: Windows Event Log Application
id: fc387a6f-0706-49d4-b97f-739144767075
version: 1
date: '2024-07-18'
author: Patrick Bareiss, Splunk
source: XmlWinEventLog:Application
sourcetype: XmlWinEventLog
separator: EventCode
supported_TA:
- name: Splunk Add-on for Microsoft Windows
  url: https://splunkbase.splunk.com/app/742
  version: 8.8.0
description: Data source object for Windows Event Log Application
event_sources:
- Windows Event Log Application 2282
- Windows Event Log Application 3000
