Detections:
- changed-files:
  - any-glob-to-any-file: 
    - detections/**
    - dev/**

Stories:
- changed-files:
  - any-glob-to-any-file: stories/*

Playbooks:
- changed-files:
  - any-glob-to-any-file: playbooks/*

Macros:
- changed-files:
  - any-glob-to-any-file: macros/*

Lookups:
- changed-files:
  - any-glob-to-any-file: lookups/*