variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - validate

validate:
  stage: validate
  image: python:3.7
  before_script:
    - pip3 install -r requirements.txt
  script:
    - python3 bin/validate.py -p . -v


