# GitLab checks out the repo in a HEAD-less state, so we must checkout the source ref for dry-run 
# to work
.checkout-source-branch:
  before_script:
      - >
        git fetch origin $CI_MERGE_REQUEST_TARGET_BRANCH_NAME &&
        git fetch origin $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME &&
        git checkout $CI_MERGE_REQUEST_TARGET_BRANCH_NAME &&
        git checkout $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME &&
        GIT_HEAD=$(git rev-parse HEAD) &&
        if [ "$GIT_HEAD" = "$CI_COMMIT_SHA" ]; then
          echo "HEAD ${GIT_HEAD} matches pipeline commit sha ${CI_COMMIT_SHA}";
        else
          echo "HEAD ${GIT_HEAD} DOES NOT match pipeline commit sha ${CI_COMMIT_SHA}";
          exit 1;
        fi