# Install contentctl w/ pip
.install-contentctl:
  before_script: |
      python3.11 -m venv .venv
      source .venv/bin/activate
      pip install contentctl==4.1.3
      git clone --depth=1 --single-branch --branch=master https://github.com/redcanaryco/atomic-red-team.git
