---

- name: Delete ESCU APP
  file:
    state: absent
    path: "/opt/splunk/etc/apps/DA-ESS-ContentUpdate"
  become: yes

- name: Upload ESCU APP
  copy:
    src: ../../../{{ security_content_path }}/dist/escu/
    dest: "/opt/splunk/etc/apps/DA-ESS-ContentUpdate"
    owner: splunk
    group: splunk
  become: yes

- name: make /opt writetable by splunk
  become: true
  file: path=/opt/splunk/etc/system/local/ mode=777

- name: copy props.conf to fix XMLWinEventlog parsing issue
  copy:
    src: props.conf
    dest: /opt/splunk/etc/system/local/props.conf
    owner: splunk
    group: splunk
    force: yes
  become: yes

- name: restart containerized splunk
  ansible.builtin.shell: echo "[XmlWinEventLog]" >  /opt/splunk/etc/system/local/props.conf && echo "BREAK_ONLY_BEFORE=<Event\sxmlns" >> /opt/splunk/etc/system/local/props.conf && /opt/splunk/bin/splunk restart
  become: yes

- name: restart splunk
  service:
    name: splunkd
    state: restarted
  become: yes

