# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

dependencies:
  cache_directories:
    - "~/.apt-cache"
  pre:
    - sudo rm -rf /var/cache/apt/archives && sudo ln -s ~/.apt-cache /var/cache/apt/archives && mkdir -p ~/.apt-cache/partial

apt-run: &apt-install
  name: install system packages
  command: |
    sudo apt update
    sudo apt install -y enchant

version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:2.7.13

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - run:
          name: checkout repo
          command: |
            git clone --branch ${CIRCLE_BRANCH} https://${GITHUB_TOKEN}@github.com/splunk/security-content.git

      - run: *apt-install

      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "security-content/requirements.txt" }}
      - run:
          name: install python dependencies
          command: |
            cd security-content
            rm -rf venv
            virtualenv --clear venv
            source venv/bin/activate
            pip install -q -r requirements.txt
      - run:
          name: run validate manifest
          command: |
            cd security-content
            source venv/bin/activate
            python bin/validate_manifests.py
      - run:
          name: run manifest to escu
          command: |
            cd security-content
            source venv/bin/activate
            python bin/manifest_to_escu.py
      - run:
          name: run manifest to usecase library
          command: |
            cd security-content
            source venv/bin/activate
            python bin/manifest_to_usecaselibrary.py
      - run:
          name: store updated analyticstories.conf
          command: |
            cd security-content
            git config credential.helper 'cache --timeout=120'
            git config user.email "research@splunk.com"
            git config user.name "Deployment Bot"
            git commit --allow-empty -m "updating src files [skip ci]"
            # Push quietly to prevent showing the token in log
            git push https://${GITHUB_TOKEN}@github.com/splunk/security-content.git ${CIRCLE_BRANCH}
      - store_artifacts:
          path: ~/repo/src/default/analyticstories.conf
          destination: src/default/analyticstories.conf
      - store_artifacts:
          path: ~/repo/src/default/analytic_stories.conf
          destination: src/default/analytic_stories.conf
      - store_artifacts:
          path: ~/repo/src/default/savedsearches.conf
          destination: src/default/savedsearches.conf
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "security-content/requirements.txt" }}
          paths:
            - "venv"
