# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

dependencies:
  cache_directories:
    - "~/.apt-cache"
  pre:
    - sudo rm -rf /var/cache/apt/archives && sudo ln -s ~/.apt-cache /var/cache/apt/archives && mkdir -p ~/.apt-cache/partial

apt-run: &apt-install
  name: install system packages
  command: |
    sudo apt update
    sudo apt install -y enchant

version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:2.7.13

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      - run: *apt-install

      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: install python dependencies
          command: |
            rm -rf venv
            virtualenv --clear venv
            source venv/bin/activate
            pip install -q -r requirements.txt
      - run:
          name: run validate manifest
          command: |
            source venv/bin/activate
            python bin/validate_manifests.py
      - run:
          name: run manifest to escu
          command: |
            source venv/bin/activate
            python bin/manifest_to_escu.py
      - store_artifacts:
          path: ~/repo/src/default/analyticstories.conf
          destination: src/default/analyticstories.conf
      - store_artifacts:
          path: ~/repo/src/default/analytic_stories.conf
          destination: src/default/analytic_stories.conf
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
