definition: eventtype="wineventlog_security"
description: Customer specific splunk configurations(eg- index, source, sourcetype) for Windows Event Logs. Replace the macro definition with configurations for your Splunk Environmnent.
name: wineventlog_security
