name: Azure AD Locking Account
id: f15e4ab7-b057-4225-86ae-c36ab78b50f2
version: 1
date: '2023-05-08'
author: Teoderick Contreras, Splunk
type: Investigation
description: "Accepts user, to be disabled using Azure AD Graph connector. This playbook produces a normalized observables output for each user and device."
playbook: Azure_AD_Locking_Account
how_to_implement: This input playbook requires the Azure AD Graph connector to be configured. 
  It is designed to work in conjunction with the Dynamic Attribute Lookup playbook or other playbooks in the same style. 
references: []
app_list: 
  - Azure AD Graph API
tags:
  platform_tags:
    - user
    - D3-AL
    - azure_ad_graph
    - disable_account
  playbook_type: Input
  vpe_type: Modern
  playbook_fields: []
  product:
  - Splunk SOAR