name: Splunk protocol impersonation weak encryption configuration
id: 839d12a6-b119-4d44-ac4f-13eed95412c8
version: 1
date: '2022-05-24'
author: Rod Soto, Splunk
type: TTP
datamodel: []
search: 'index=_internal sourcetype=splunkd event_message="*SSL*" AND event_message="*ERROR*" OR event_message="*unknown CA*" |stats count by host source component event_message | dedup component host'
description: On .
how_to_implement: This detection does not require you to ingest any new data. The detection does require the ability to search the _internal index. This search will provide search UI requests with path traversal parameter ("../../../../../../../../../") which shows exploitation attempts.
known_false_positives: This search may find additional path traversal exploitation attempts.
references:
- https://www.splunk.com/en_us/product-security/announcements/svd-2022-0506.html
tags:
  analytic_story:
  - Splunk Vulnerabilities
  asset_type: Endpoint
  cve:
  - CVE-2022-0000
  cis20:
  - CIS 3
  - CIS 5
  - CIS 16
  confidence: 80
  context:
  - Source:Endpoint
  dataset:
  - https://raw.githubusercontent.com/splunk/attack_data/master/datasets/attack_techniques/T1083/splunk/path_traversal_spl_injection.txt
  impact: 50
  kill_chain_phases:
  - Exploitation
  message: Path traversal exploitation attempt from $clientip$
  mitre_attack_id:
  - T1083
  observable:
  - name: clientip
    type: IP Address
    role:
    - Attacker
  product:
  - Splunk Enterprise
  - Splunk Enterprise Security
  - Splunk Cloud
  required_fields:
  - status
  - clientip
  - method
  - uri_path
  - uri_query
  risk_score: 40
  security_domain: threat
