name: Detect Rundll32 Application Control Bypass - advpack
id: 4aefadfe-9abd-4bf8-b3fd-867e9ef95bf8
version: 1
date: '2021-02-04'
description: The following analytic identifies rundll32.exe loading advpack.dll
  and ieadvpack.dll by calling the LaunchINFSection function. This particular technique will load
  script code from a file. Upon a successful execution, the following module loads
  may occur - clr.dll, jscript.dll and scrobj.dll. During investigation, identify
  script content origination. Generally, a child process will spawn from rundll32.exe,
  but that may be bypassed based on script code contents. 
  Rundll32.exe is natively found in C:\Windows\system32 and
  C:\Windows\syswow64.
how_to_implement: To successfully implement this search, you need to be ingesting
  logs with the process name, parent process, and command-line executions from your
  endpoints. If you are using Sysmon, you must have at least version 6.0.4 of the
  Sysmon TA. 
type: ESCU
references:
- https://attack.mitre.org/techniques/T1218/011/
- https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1218.011/T1218.011.md
- https://lolbas-project.github.io/lolbas/Binaries/Rundll32
- https://lolbas-project.github.io/lolbas/Libraries/Advpack/
- https://bohops.com/2018/02/26/leveraging-inf-sct-fetch-execute-techniques-for-bypass-evasion-persistence/
author: Michael Haag, Splunk
search: '`sysmon` EventID=1 (OriginalFileName=RUNDLL32.EXE process_name=rundll32.exe) CommandLine=*advpack*
  | stats count min(_time) as firstTime max(_time) as lastTime by Computer, User,
  parent_process_name, process_name, OriginalFileName, process_path, CommandLine |
  rename Computer as dest | `security_content_ctime(firstTime)`| `security_content_ctime(lastTime)`|
  `detect_rundll32_application_control_bypass___advpack_filter`'
known_false_positives: Although unlikely, some legitimate applications may use a moved
  copy of rundll32, triggering a false positive.
tags:
  analytics_story:
  - Suspicious Rundll32 Activity
  mitre_attack_id:
  - T1218.011
  kill_chain_phases:
  - Actions on Objectives
  cis20:
  - CIS 8
  nist:
  - PR.PT
  - DE.CM
  security_domain: endpoint
  asset_type: Endpoint
  dataset:
  - https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1218.011/windows-sysmon.log
