name: Linux Auditd Possible Access Or Modification Of Sshd Config File
id: acb3ea33-70f7-47aa-b335-643b3aebcb2f
version: 1
date: '2024-08-09'
author: Teoderick Contreras, Splunk
status: production
type: Anomaly
description: The following analytic detects suspicious access or modification of the
  sshd_config file on Linux systems. It leverages data from Endpoint Detection and
  Response (EDR) agents, focusing on command-line executions involving processes like
  "cat," "nano," "vim," and "vi" accessing the sshd_config file. This activity is
  significant because unauthorized changes to sshd_config can allow threat actors
  to redirect port connections or use unauthorized keys, potentially compromising
  the system. If confirmed malicious, this could lead to unauthorized access, privilege
  escalation, or persistent backdoor access, posing a severe security risk.
data_source:
- Linux Auditd Path
search: '`linux_auditd` type=PATH name="/etc/ssh/ssh_config*" | stats count min(_time)
  as firstTime max(_time) as lastTime by name nametype OGID | `security_content_ctime(firstTime)`|
  `security_content_ctime(lastTime)`| `linux_auditd_possible_access_or_modification_of_sshd_config_file_filter`'
how_to_implement: The detection is based on data that originates from Endpoint Detection
  and Response (EDR) agents. These agents are designed to provide security-related
  telemetry from the endpoints where the agent is installed. To implement this search,
  you must ingest logs that contain the process complete command-line executions.
  These logs must be processed using the appropriate Splunk Technology Add-ons that
  are specific to the EDR product. Use the Splunk Common Information Model (CIM) to
  normalize the field names and speed up the data modeling process.
known_false_positives: Administrator or network operator can use this commandline
  for automation purposes. Please update the filter macros to remove false positives.
references:
- https://www.hackingarticles.in/ssh-penetration-testing-port-22/
- https://attack.mitre.org/techniques/T1098/004/
tags:
  analytic_story:
  - Linux Privilege Escalation
  - Linux Persistence Techniques
  - Linux Living Off The Land
  asset_type: Endpoint
  confidence: 50
  impact: 50
  message: a $PATH$ has been accessed/modified on host.
  mitre_attack_id:
  - T1098.004
  - T1098
  observable:
  - name: name
    type: Other
    role:
    - Victim
  product:
  - Splunk Enterprise
  - Splunk Enterprise Security
  - Splunk Cloud
  required_fields:
  - _time
  - name
  - nametype
  - OGID
  risk_score: 25
  security_domain: endpoint
tests:
- name: True Positive Test
  attack_data:
  - data: https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1098.004/linux_auditd_nopasswd/linux_auditd_ssh_config.log
    source: /var/log/audit/audit.log
    sourcetype: linux:audit
