name: Office Application Spawned CMD Shell
id: c1ad8f62-9c65-11eb-9d59-acde48001122
version: 1
date: '2021-04-13'
author: Teoderick Contreras, Splunk
type: batch
datamodel:
- Endpoint
description: this search is to detect a potential malicious office macro document that spawn command shell to execute malicious batch, powershell, vb/js script.
  this technique is common on malicious ms office macro document used by threat actor to load payloads, download payloads or other malware.
search: '| tstats `security_content_summariesonly` count values(Processes.process) min(_time) as firstTime max(_time) as lastTime from datamodel=Endpoint.Processes
  where (Processes.parent_process_name = "winword.exe" OR Processes.parent_process_name = "excel.exe" OR Processes.parent_process_name = "powerpnt.exe" OR Processes.parent_process_name = "wordpad.exe") 
  Processes.process_name= "cmd.exe"  by Processes.parent_process Processes.process_name Processes.process_id Processes.process_guid
  Processes.user Processes.dest 
  | `drop_dm_object_name("Processes")` 
  | `security_content_ctime(firstTime)`
  |`security_content_ctime(lastTime)` 
  | `office_application_spawned_cmd_shell_filter`'
how_to_implement: To successfully implement this search, you need to be ingesting
  logs with the process name, parent process, and command-line executions from your
  endpoints. If you are using Sysmon, you must have at least version 6.0.4 of the
  Sysmon TA. Tune and filter known instances where renamed cmd.exe may be used.
known_false_positives: office document that load automation batch script
references:
- https://www.joesandbox.com/analysis/369141/0/html
tags:
  analytic_story:
  - Spearphishing Attachments
  kill_chain_phases:
  - Exploitation
  mitre_attack_id:
  - T1566.001
  product:
  - Splunk Enterprise
  - Splunk Enterprise Security
  - Splunk Cloud
  required_fields:
  - Processes.process
  - Processes.parent_process_name
  - _time
  - Processes.process_name
  - Processes.dest
  - Processes.user
  - Processes.process_id
  security_domain: endpoint