name: Windows Ingress Tool Transfer Using Explorer.exe
id: 76753bab-f116-4ea3-8fb9-89b638be58a9
version: 1
date: '2022-08-01'
author: Teoderick Contreras, Splunk
type: Anomaly
datamodel:
- Endpoint
description: The following analytic detects a explorer.exe with possible url link process commandline on it. 
  Explorer.exe is known windows process that handle start menu, taskbar ,desktop and file manager. 
  So many threat actor abuses this process like DCRat malware, where it tries to open the url link with the default process browser application 
  in the target host by putting the url link as a parameter on explorer.exe process. This anomaly detection might be a good pivot to check 
  which user and how this process was executed, what is the parent process and what is the url link. This technique is not so common way to open an url link.
search: '| tstats `security_content_summariesonly` min(_time) as firstTime max(_time) as lastTime from datamodel=Endpoint.Processes
  where (Processes.process_name = explorer.exe OR Processes.original_file_name = explorer.exe) AND NOT (Processes.parent_process_name IN("userinit.exe", "svchost.exe")) Processes.process IN ("* http://*", "* https://*")
  by  Processes.parent_process_name Processes.parent_process Processes.process_name Processes.original_file_name Processes.process Processes.process_id Processes.parent_process_id Processes.dest Processes.user
  | `drop_dm_object_name(Processes)` 
  | `security_content_ctime(firstTime)` 
  | `security_content_ctime(lastTime)` 
  | `windows_ingress_tool_transfer_using_explorer_exe_filter`'
how_to_implement: To successfully implement this search, you need to be ingesting
  logs with the process name, parent process, and command-line executions from your
  endpoints. If you are using Sysmon, you must have at least version 6.0.4 of the
  Sysmon TA.
known_false_positives: unknown
references:
- https://www.mandiant.com/resources/analyzing-dark-crystal-rat-backdoor
tags:
  analytic_story:
  - DarkCrystal RAT
  asset_type: Endpoint
  cis20:
  - CIS 3
  - CIS 5
  - CIS 16
  confidence: 50
  context:
  - Source:Endpoint
  - Stage:Execution
  dataset:
  - https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/malware/dcrat/dcrat_explorer_url/sysmon.log
  impact: 50
  kill_chain_phases:
  - Exploitation
  message: a explorer process with url link $process$ in $dest$
  mitre_attack_id:
  - T1105
  nist:
  - DE.CM
  observable:
  - name: dest
    type: Hostname
    role:
    - Victim
  product:
  - Splunk Enterprise
  - Splunk Enterprise Security
  - Splunk Cloud
  required_fields:
  - _time
  - Processes.dest
  - Processes.user
  - Processes.parent_process_name
  - Processes.parent_process
  - Processes.original_file_name
  - Processes.process_name
  - Processes.process
  - Processes.process_id
  - Processes.parent_process_path
  - Processes.process_path
  - Processes.parent_process_id
  risk_score: 25
  security_domain: endpoint
