name: auto-update
on:
  push: {}
jobs:
  
  validate-tag-if-present:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - name: TAGGED, Validate that the tag is in the correct format
        
        run: |
          #Run and exit cleanly if it matches vNUMBER.NUMBER.NUMBER syntax
          [[ $GITHUB_REF =~ refs/tags/v[0-9]+.[0-9]+.[0-9]+ ]] && exit
          #If it does not, then return 1, which will kill the rest of the steps
          exit 1
        
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-18.04
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          DRY_RUN: "false"
          MERGE_MSG: "Branch was auto-updated."
