name: docker-detection-testing
on:
  push:
jobs:

  validate-tag-if-present:
    runs-on: ubuntu-latest

    steps:
      - name: TAGGED, Validate that the tag is in the correct format
        
        run: |
          echo "The GITHUB_REF: $GITHUB_REF"
          #First check to see if the release is a tag
          if [[ $GITHUB_REF =~ refs/tags/* ]]; then
            #Yes, this is a tag, so we need to test to make sure that the tag
            #is in the correct format (like v1.10.20)
            if [[ $GITHUB_REF =~ refs/tags/v[0-9]+.[0-9]+.[0-9]+ ]]; then
              echo "PASS: Tagged release with good format"
              exit 0
            else
              echo "FAIL: Tagged release with bad format"
              exit 1
            fi
          else
          echo "PASS: Not a tagged release"
          exit 0
          fi                    
  
  quit-for-dependabot:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
    steps:
      - name: "Placeholder"
        run: |
          echo "No, this is not a dependabot run!"


  docker-detection-testing-setup:
      runs-on: ubuntu-latest
      needs: [validate-tag-if-present, quit-for-dependabot]
      steps:  
          - name: Get branch and PR required for detection testing main.py
            id: vars
            run: |
              echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"

          - name: Checkout Repo
            uses: actions/checkout@v2
          
          - name: Install Docker 
            run: |
              sudo apt update -qq
              

              #python2.7 needed for slim, for now
              sudo apt install python2
              sudo apt install virtualenv 
              curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
              sudo python2.7 get-pip.py

          - uses: actions/setup-python@v2
            with:
              python-version: '3.9' #Available versions here - https://github.com/actions/python-versions/releases  easy to change/make a matrix/use pypy
              architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified          
          
          - name: Install Python Dependencies
            run: |
              cd automated_detection_testing/ci/detection_testing_batch
              python3 -m venv .venv
              source .venv/bin/activate
              python3 -m pip install wheel
              python3 -m pip install -r requirements.txt
          
          - name: Run the CI
            run: |
              cd automated_detection_testing/ci/detection_testing_batch
              source .venv/bin/activate
              
              python3 detection_testing_execution.py run --branch develop  --mode changes --num_containers 10 --mock 
          
          - name: Upload Test Results Files
            uses: actions/upload-artifact@v2
            with:
              name: testing-results-config
              path: |
                automated_detection_testing/ci/detection_testing_batch/prior_config/apps/DA-ESS-ContentUpdate-latest.tar.gz
                automated_detection_testing/ci/detection_testing_batch/prior_config/config_tests_0.json
                automated_detection_testing/ci/detection_testing_batch/prior_config/config_tests_1.json
                automated_detection_testing/ci/detection_testing_batch/prior_config/config_tests_2.json
                automated_detection_testing/ci/detection_testing_batch/prior_config/config_tests_3.json
                automated_detection_testing/ci/detection_testing_batch/prior_config/config_tests_4.json
                automated_detection_testing/ci/detection_testing_batch/prior_config/config_tests_5.json
                automated_detection_testing/ci/detection_testing_batch/prior_config/config_tests_6.json
                automated_detection_testing/ci/detection_testing_batch/prior_config/config_tests_7.json
                automated_detection_testing/ci/detection_testing_batch/prior_config/config_tests_8.json
                automated_detection_testing/ci/detection_testing_batch/prior_config/config_tests_9.json

  docker-detection-testing-execution:
    runs-on: ubuntu-latest
    needs: [validate-tag-if-present, quit-for-dependabot, docker-detection-testing-setup]
    strategy:
      matrix:
        manifest_filename: ["config_tests_0.json", 
                        "config_tests_1.json",
                        "config_tests_2.json",
                        "config_tests_3.json",
                        "config_tests_4.json",
                        "config_tests_5.json",
                        "config_tests_6.json",
                        "config_tests_7.json",
                        "config_tests_8.json",
                        "config_tests_9.json"]
    steps:  
        - name: Get branch and PR required for detection testing main.py
          id: vars
          run: |
            echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"

        - name: Checkout Repo
          uses: actions/checkout@v2
        
        - name: Download artifacts
          uses: actions/download-artifact@v2
          with:
            name: testing-results-config
            path: automated_detection_testing/ci/detection_testing_batch/prior_config
        - name: Install Docker 
          run: |
            sudo apt update -qq
            

            #python2.7 needed for slim, for now
            sudo apt install python2
            sudo apt install virtualenv 
            curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
            sudo python2.7 get-pip.py

        - uses: actions/setup-python@v2
          with:
            python-version: '3.9' #Available versions here - https://github.com/actions/python-versions/releases  easy to change/make a matrix/use pypy
            architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified          
        
        - name: Install Python Dependencies
          run: |
            cd automated_detection_testing/ci/detection_testing_batch
            python3 -m venv .venv
            source .venv/bin/activate
            python3 -m pip install wheel
            python3 -m pip install -r requirements.txt
        
        - name: Run the CI
          run: |
            cd automated_detection_testing/ci/detection_testing_batch
            source .venv/bin/activate
            
            python3 detection_testing_execution.py run -c prior_config/${{ matrix.manifest_filename}} --splunkbase_username ${{ secrets.SPLUNKBASE_TESTING_USERNAME }} --splunkbase_password ${{ secrets.SPLUNKBASE_TESTING_KEY }} 
                    
        
        - name: Upload Test Results Files
          uses: actions/upload-artifact@v2
          with:
            name: ${{ matrix.manifest_filename}}.results
            path: |
              automated_detection_testing/ci/detection_testing_batch/success.csv
              automated_detection_testing/ci/detection_testing_batch/error.csv
              automated_detection_testing/ci/detection_testing_batch/failure.csv
              automated_detection_testing/ci/detection_testing_batch/combined.csv
              automated_detection_testing/ci/detection_testing_batch/success.json
              automated_detection_testing/ci/detection_testing_batch/error.json
              automated_detection_testing/ci/detection_testing_batch/failure.json
              automated_detection_testing/ci/detection_testing_batch/combined.json
          
  docker-detection-testing-execution-merge-results:
    runs-on: ubuntu-latest
    needs: [validate-tag-if-present, quit-for-dependabot, docker-detection-testing-setup, docker-detection-testing-execution]
 
    steps:  
        - name: Get branch and PR required for detection testing main.py
          id: vars
          run: |
            echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"

        - name: Checkout Repo
          uses: actions/checkout@v2
        
        - name: Download artifacts
          uses: actions/download-artifact@v2
          with:
            name: config_tests_0.json.results
            path: automated_detection_testing/ci/detection_testing_batch/results_0
        - name: Download artifacts
          uses: actions/download-artifact@v2
          with:
            name: config_tests_1.json.results
            path: automated_detection_testing/ci/detection_testing_batch/results_1
        - name: Download artifacts
          uses: actions/download-artifact@v2
          with:
            name: config_tests_2.json.results
            path: automated_detection_testing/ci/detection_testing_batch/results_2
        - name: Download artifacts
          uses: actions/download-artifact@v2
          with:
            name: config_tests_3.json.results
            path: automated_detection_testing/ci/detection_testing_batch/results_3
        - name: Download artifacts
          uses: actions/download-artifact@v2
          with:
            name: config_tests_4.json.results
            path: automated_detection_testing/ci/detection_testing_batch/results_4
        - name: Download artifacts
          uses: actions/download-artifact@v2
          with:
            name: config_tests_5.json.results
            path: automated_detection_testing/ci/detection_testing_batch/results_5
        - name: Download artifacts
          uses: actions/download-artifact@v2
          with:
            name: config_tests_6.json.results
            path: automated_detection_testing/ci/detection_testing_batch/results_6
        - name: Download artifacts
          uses: actions/download-artifact@v2
          with:
            name: config_tests_7.json.results
            path: automated_detection_testing/ci/detection_testing_batch/results_7
        - name: Download artifacts
          uses: actions/download-artifact@v2
          with:
            name: config_tests_8.json.results
            path: automated_detection_testing/ci/detection_testing_batch/results_8
        - name: Download artifacts
          uses: actions/download-artifact@v2
          with:
            name: config_tests_9.json.results
            path: automated_detection_testing/ci/detection_testing_batch/results_9
        
        - uses: actions/setup-python@v2
          with:
            python-version: '3.9' #Available versions here - https://github.com/actions/python-versions/releases  easy to change/make a matrix/use pypy
            architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified    

        - name: Merge Detections into single File
          run: |
            cd automated_detection_testing/ci/detection_testing_batch
            python summarize_json.py --files results_*/combined.json --output_filename summary_test_results.json
            
            
        - name: Upload Summary Test Results JSON
          uses: actions/upload-artifact@v2
          if: always()
          with:
            name: SummaryTestResults
            path: |
              automated_detection_testing/ci/detection_testing_batch/summary_test_results.json
        
        - name: Clean up intermediate Files
          uses: geekyeggo/delete-artifact@v1
          if: always()
          with:
              name: |
                config_tests_0.json.results
                config_tests_1.json.results
                config_tests_2.json.results
                config_tests_3.json.results
                config_tests_4.json.results
                config_tests_5.json.results
                config_tests_6.json.results
                config_tests_7.json.results
                config_tests_8.json.results
                config_tests_9.json.results
                