name: Windows Ingress Tool Transfer Using Explorer
id: 76753bab-f116-4ea3-8fb9-89b638be58a9
version: 2
date: '2022-08-30'
author: Teoderick Contreras, Splunk
status: production
type: Anomaly
description: The following analytic identifies the Windows Explorer process with a
  URL within the command-line. Explorer.exe is known Windows process that handles
  start menu, taskbar, desktop and file manager. Many adversaries abuse this process,
  like DCRat malware, where it attempts to open the URL with the default browser application
  on the target host by putting the URL as a parameter on explorer.exe process. This
  anomaly detection might be a good pivot to check which user and how this process
  was executed, what is the parent process and what is the URL link. This technique
  is not commonly used to open an URL.
data_source:
- Sysmon Event ID 1
search: '| tstats `security_content_summariesonly` min(_time) as firstTime max(_time)
  as lastTime from datamodel=Endpoint.Processes where (Processes.process_name = explorer.exe
  OR Processes.original_file_name = explorer.exe) AND NOT (Processes.parent_process_name
  IN("userinit.exe", "svchost.exe")) Processes.process IN ("* http://*", "* https://*")
  by  Processes.parent_process_name Processes.parent_process Processes.process_name
  Processes.original_file_name Processes.process Processes.process_id Processes.parent_process_id
  Processes.dest Processes.user | `drop_dm_object_name(Processes)` | `security_content_ctime(firstTime)`
  | `security_content_ctime(lastTime)` | `windows_ingress_tool_transfer_using_explorer_filter`'
how_to_implement: To successfully implement this search you need to be ingesting information
  on process that include the name of the process responsible for the changes from
  your endpoints into the `Endpoint` datamodel in the `Processes` node. In addition,
  confirm the latest CIM App 4.20 or higher is installed and the latest TA for the
  endpoint product.
known_false_positives: False positives may be present based on legitimate applications
  or third party utilities. Filter out any additional parent process names.
references:
- https://www.mandiant.com/resources/analyzing-dark-crystal-rat-backdoor
tags:
  analytic_story:
  - DarkCrystal RAT
  asset_type: Endpoint
  atomic_guid: []
  drilldown_search: []
  message: An instance of $parent_process_name$ spawning $process_name$ was identified
    on endpoint $dest$ by user $user$ attempting to download a remote payload.
  mitre_attack_id:
  - T1105
  product:
  - Splunk Enterprise
  - Splunk Enterprise Security
  - Splunk Cloud
  risk_score: 25
  security_domain: endpoint
tests:
- name: True Positive Test
  attack_data:
  - data: https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1105/atomic_red_team/T1105_explorer-windows-security.log
    source: XmlWinEventLog
    sourcetype: XmlWinEventLog
    update_timestamp: true
